### PR TITLE
Created build on RasPi doc

### PR DESCRIPTION
**Pull request by okyeron**
Detailed instructions for building norns on Rasberry Pi

Included all instructions from other norns locations to make it easier for someone to walk thru the process.

### CODE REVIEW

**Comment by cmcavoy** [comment]
bitmoji

**Comment by okyeron** [comment]
fixes #52

**Comment by lazzarello** [comment]
It appears the `libnanomsg-dev` package is not compatible with pkg-config. The step to build the norns repo with `./waf configure` fails with the following output

```
Checking for 'nanomsg'
['/usr/bin/pkg-config', '--cflags', '--libs', 'nanomsg']
err: Package nanomsg was not found in the pkg-config search path.
Perhaps you should add the directory containing `nanomsg.pc'
to the PKG_CONFIG_PATH environment variable
No package 'nanomsg' found

not found
from /home/we/norns: The configuration failed
```

The version in Debian is named libnanomsg

```
we@bleh:~/norns$ locate nanomsg.pc
/usr/lib/arm-linux-gnueabihf/pkgconfig/libnanomsg.pc
``

I suspect that @catfact has made a custom build of this package?

**Comment by okyeron** [comment]
I did not run into this issue when compiling on RasPi a few weeks ago. 

However,  when I tried making a Vagrant installation with Debian, I ended up having to build libmonome and nanomsg from source. 

Perhaps something has changed?

**Comment by lazzarello** [comment]
The `libnanomsg-dev` package in Debian has a different API than the upstream `master` branch. @catfact built a Debian package and hosted it on a repo, which was offline last night when I was building stuff.

**Comment by tehn** [comment]
see the `buster` branch for updated build instructions. (also i suspect this is largely stale after norns-shield and fates)

**Pull request closed without merging**
